"""add exchange to stocks

Revision ID: 01df0a7bf349
Revises: cb1a22af134c
Create Date: 2026-08-25 01:44:42.655978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01df0a7bf349'
down_revision: Union[str, Sequence[str], None] = 'cb1a22af134c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('exchange', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'exchange')
    # ### end Alembic commands ###
