"""add refresh_status table

Revision ID: 41a2a1ccb558
Revises: dd8a7a949707
Create Date: 2026-08-19 18:00:30.885782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41a2a1ccb558'
down_revision: Union[str, Sequence[str], None] = 'dd8a7a949707'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_succeeded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('had_failures', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refresh_status')
    # ### end Alembic commands ###
