"""add screener change_7d_pct

Revision ID: 86f945a068ae
Revises: 01df0a7bf349
Create Date: 2026-08-26 11:30:11.427901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86f945a068ae'
down_revision: Union[str, Sequence[str], None] = '01df0a7bf349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screener_results', sa.Column('change_7d_pct', sa.Numeric(precision=8, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screener_results', 'change_7d_pct')
    # ### end Alembic commands ###
