"""initial schema: stocks, daily_prices, trades, settings, profit_targets

Revision ID: dd8a7a949707
Revises: 
Create Date: 2026-08-19 13:37:02.890306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd8a7a949707'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('default_profit_target_dollars', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('investor_relations_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_ticker'), 'stocks', ['ticker'], unique=True)
    op.create_table('daily_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'trade_date', name='uq_daily_price_stock_date')
    )
    op.create_index(op.f('ix_daily_prices_stock_id'), 'daily_prices', ['stock_id'], unique=False)
    op.create_table('profit_targets',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('target_dollars', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('stock_id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=4), nullable=False),
    sa.Column('shares', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('price_per_share', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('buy', 'sell')", name='ck_trade_action_valid'),
    sa.CheckConstraint('price_per_share > 0', name='ck_trade_price_positive'),
    sa.CheckConstraint('shares > 0', name='ck_trade_shares_positive'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_stock_id'), 'trades', ['stock_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_stock_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_table('profit_targets')
    op.drop_index(op.f('ix_daily_prices_stock_id'), table_name='daily_prices')
    op.drop_table('daily_prices')
    op.drop_index(op.f('ix_stocks_ticker'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_table('settings')
    # ### end Alembic commands ###
